[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
md5 = "0.7.0"
petgraph = "0.6.5"
regex = "1.11.1"
rustc-hash = "2.1.0"
strip-ansi-escapes = "0.2.0"
tabled = "0.17.0"
