[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.2.0"
fxhash = "0.2.1"
md5 = "0.7.0"
num = "0.4.3"
regex = "1.11.1"
strip-ansi-escapes = "0.2.0"
tabled = "0.17.0"
